sudo: false
language:
  - node_js
node_js:
  - v5.9.1
install:
  - npm install
script:
  - npm run test-$TEST_SUITE
env:
  matrix:
  - TEST_SUITE=unit
  - TEST_SUITE=integration
cache:
  directories:
    - node_modules
services:
  postgresql
before_script:
  - psql -c 'create database barbu-test;' -U postgres
