sudo: false
language:
  - node_js
node_js:
  - v5.9.1
install:
  - npm install
script:
  - npm run test-$TEST_SUITE
env:
  matrix:
  - CC=clang CXX=clang++ npm_config_clang=1 TEST_SUITE=unit
  - CC=clang CXX=clang++ npm_config_clang=1 TEST_SUITE=integration
cache:
  directories:
    - node_modules
services:
  postgresql
